name: java
type: "java:8"

disk: 1024

hooks:
  build: mvn clean install -U

relationships:
  database: 'mysql:mysql'
  postgresql: 'postgresql:postgresql'
  mongodb: 'mongodb:mongodb'
  redis: 'redis:redis'
  elasticsearch: 'elasticsearch:elasticsearch'
  memcached: 'memcached:memcached'
  solr: 'solr:solr'
  rabbitmq: 'rabbitmq:rabbitmq'
  influxdb: 'influxdb:influxdb'
  kafka: 'kafka:kafka'


web:
  commands:
    start:  java -jar target/java-language-example.jar --server.port=$PORT
