name: app
type: "java:8"

disk: 1024

hooks:
    build: mvn clean install
    
relationships:
    database: "database:mysql"
web:
    commands:
        start:  java -jar target/spring-mvc-mysql-0.0.1.jar --server.port=$PORT
