version:  '3.2'

services:

  redis:
    image: "redis:latest"
    networks:
      - javanet
    ports:
      - 6379:6379

  mysql:
    image: "mysql:latest"
    networks:
      - javanet
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: people
    ports:
      - 3306:3306

  postgresql:
    image: "postgres:latest"
    networks:
      - javanet
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: people
    ports:
      - 5432:5432

  mongo:
    image: "mongo:latest"
    networks:
      - javanet
    ports:
      - 27017:27017

  elasticsearch:
    image: "elasticsearch:7.1.0"
    networks:
      - javanet
    ports:
      - 9200:9200
      - 9300:9300

  sorl:
    image: "solr:latest"
    networks:
      - javanet
    ports:
      - 8983:8983

  memcached:
    image: "memcached:latest"
    networks:
      - javanet
    ports:
      - 11211:11211



networks:
  javanet:
